### ISSUE TITLE
Support custom annotations

### ISSUE THREAD

**Issue by tokyowizard** [volker-raschek/drone-charts#7]
Thank you again for the charts!

The ingress resource already has this support. https://github.com/volker-raschek/drone-charts/blob/master/templates/ingress.yaml#L21-L24

Could the rest of the resources have custom annotations support in particular the service account? https://github.com/volker-raschek/drone-charts/blob/master/templates/serviceAccount.yaml

**Comment by volker-raschek** [comment]
Hi @tokyowizard,
I released for some minutes the chart version 0.6.1 to set additional labels for `service` and `serviceAccount`. Please check it out if it works for you.

**Comment by tokyowizard** [comment]
That works, thank you!

It might be nice to consolidate them into one variable or something later, because the values in the `values.yaml` repeats:

```
ingress:
  enabled: true
  annotations:
    myAnnotation: myValue

service:
  annotations:
    myAnnotation: myValue

serviceAccount:
  annotations:
    myAnnotation: myValue

podAnnotations:
    myAnnotation: myValue
```

0.6.1 works for me. Thank you, again. ❤️
